name: fastyle_calculator_example
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.1"

dependencies:
  flutter:
    sdk: flutter

  fastyle_dart: ^0.29.0
  tbloc_dart: ^0.19.0
  decimal: ^1.5.0
  tmodel_dart: ^0.4.0

  fastyle_calculator:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
