name: fastyle_calculator
description: A set of widgets with defined style.
version: 0.7.0
homepage: https://github.com/tyrcord/fastyle_calculator

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.1"

dependencies:
  flutter:
    sdk: flutter

  fastyle_dart: ^0.29.0
  tbloc_dart: ^0.19.0
  tmodel_dart: ^0.4.0
  tstore_dart: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1
  test: ^1.21.1
  dart_code_metrics: ^4.15.2
