name: fastyle_calculator
description: A new Flutter package project.
version: 0.3.1
homepage: https://github.com/tyrcord/fastyle_calculator

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter

  fastyle_dart: ^0.27.1
  tbloc_dart: ^0.18.2
  tmodel_dart: ^0.3.1
  tstore_dart: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1
  test: ^1.19.5
  dart_code_metrics: ^4.1.0
